name: SonarCloud

on: [ push, pull_request ]

jobs:
  kahypar_debug_tests:
    runs-on: ubuntu-latest
    env:
      BOOST_ROOT : "/usr/local/share/boost/1.72.0"
      CI_ACTIVE : 1
      BUILD_TYPE : "Debug"
      COV : "ON"
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory

    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v2
        with:
         fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libboost-program-options-dev lcov gcovr libpython3-all-dev cppcheck
      
      - name: Install sonar-scanner and build-wrapper
        uses: SonarSource/sonarcloud-github-c-cpp@v1

      - name: Setup KaHyPar
        run: |
          git submodule init
          git submodule update
          rm -rf debug && mkdir debug && cd debug
          cmake .. -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DKAHYPAR_ENABLE_HEAVY_PREPROCESSING_ASSERTIONS=OFF

      - name: Build KaHyPar
        run: |
          cd debug
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} make clean KaHyPar
          
      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner --define sonar.cfamily.build-wrapper-output="${{ env.BUILD_WRAPPER_OUT_DIR }}"
